### PR TITLE
To scala 2.13.0 (cross compile)

### PR DESCRIPTION
**Pull request by mathieuleclaire**
Update libraries and code for scala 2.13.0

### CODE REVIEW

**Comment by mathieuleclaire** [comment]
Justin, do you still maintain this project ?

**Comment by mathieuleclaire** [comment]
Justin, would you give me the collaborator rights if you do not maintain this lib any more ?

**Comment by exoego** [comment]
@mathieuleclaire 
Justin is more active on Twitter than on GitHub so I think you can contact him on Twitter.

**Comment by mathieuleclaire** [comment]
Thanks for the hint, but sadly it is not possible to send him private messages on Twitter. I tried with an email.

**Comment by jducoeur** [comment]
Yeah, the problem is mainly that I've taken my eye off this ball because I haven't done anything much with jsext myself lately.  (I'm still stuck on 2.11 due to stupid external dependencies.)  But I've given Mathieu collaborator status, so we can at least start moving things along.

**Comment by cquiroz** [comment]
It would be great to publish this. I tried to update `jquery-facade` to compile for 2.13 but it depends on `jsext`

**Comment by exoego** [comment]
FYI: https://github.com/exoego/scala-js-jquery support both Scala 2.12 and 2.13, and not depending on jsext.

**Comment by jducoeur** [comment]
Okay -- after far too long, I finally managed to scrape together a few hours to reconfigure my new development machine, update the library's build.sbt to match the way sbt-pgp and sbt-sonatype now work, and push the thing out the door.  Sonatype now claims to have version 0.9 cross-built for 2.10 through 2.13.

Thanks to Mathieu for pushing this along, and my apologies for how long it took for me to figure out all the needed details...

**Pull request merged**
