### PR TITLE
Enable cross-building for Scala.js 0.6 and 1.0

### PR DESCRIPTION
**Pull request by frne**
Could you please publish a Scala.js `0.6` and `1.0` version for Scala `2.12` and `2.13` accordingly?

Hope this is helpful to do it...

### CODE REVIEW

**Comment by frne** [comment]
Relates to #18

**Comment by mathieuleclaire** [comment]
Hi,
I suggest to set 
```scala
val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).getOrElse("1.0.1")
```
instead of
```scala
val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).getOrElse("0.6.32")
```

**Comment by frne** [comment]
@mathieuleclaire Already done, see second commit ;)

**Comment by mathieuleclaire** [comment]
You're right, sorry. It sounds good to me then. Thanks @frne

**Pull request merged**
